name: Compile and Test Haskell Code
on:
  push:
    branches:
      - master
    paths:
      - 'haskell/**'
      - '.github/workflows/haskell-compile-and-test.yaml'

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ghc-ver: ["9.0.1"]
        cabal-ver: ["3.4.0.0"]

    steps:

# Download this git repo
    - name: Checkout main
      uses: actions/checkout@v2

# Install GHC & Cabal
    - uses: actions/cache@v2
      name: Cache cabal packages
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          haskell/dist
          haskell/dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ hashFiles('haskell/**') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-

    - name: Install ghc and cabal
      uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Put cabal programs in PATH
      run: echo "~/.cabal/bin" >> $GITHUB_PATH

# Compile Local Haskell
    - name: Build and Test Haskell
      run: |
        cd haskell
        cabal build
        cabal test
        cabal -v new-haddock --haddock-hyperlink-source --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs' --enable-documentation

# Deploy Haskell docs to site
    - name: Deploy haddocks to github pages
      uses: peaceiris/actions-gh-pages@v3.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: haskell/dist-newstyle/build/x86_64-linux/ghc-${{ matrix.ghc-ver }}/haskell-0.1.0.0/doc/html/haskell
        destination_dir: haskell
